# Generated by Django 5.0.1 on 2024-02-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
