# Generated by Django 5.0.1 on 2024-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='EMAIL',
            field=models.CharField(max_length=50),
        ),
    ]
