# Generated by Django 5.0.1 on 2024-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_entry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='EMAIL',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
